Add possibility to upload to Harbor
kokuwaio/helm-maven-plugin pull request #113
Opened 2021-02-10 10:18 UTC by torrespro

doc: update Readme with the new upload to Harbor (via Harbor API)
feature: add Harbor to he UploadMojo (https://github.com/kiwigrid/helm-maven-plugin/issues/83)
feature: upload to Nexus, Harbor and Chartmuseum now support username/pwd from settings.xml file https://github.com/kiwigrid/helm-maven-plugin/issues/105

2021-02-10 11:44 UTC, jjjasper commented on src/main/java/com/kiwigrid/helm/maven/plugin/UploadMojo.java
> +			break;
Alternatively, `return` and have no need for the very big conditional block `if (uploadRepo.getType() != RepoType.HARBOR)`

2021-02-10 11:48 UTC, jjjasper commented on src/main/java/com/kiwigrid/helm/maven/plugin/UploadMojo.java
> +			} else {
`if` block ends with exception, no need for `else`.

2021-04-20 18:59 UTC, grdaneault commented
Hi! Any chance of an update here?

2021-04-23 06:11 UTC, axdotl requested changes

2021-04-23 06:11 UTC, axdotl commented on src/main/java/com/kiwigrid/helm/maven/plugin/UploadMojo.java
> +	protected void uploadToHarbor(File file) throws IOException, BadUploadException, MojoExecutionException {
Upload to Harbor is implemented different from other uploads.

I would prefer to get a method like
```
protected HttpURLConnection getConnectionForUploadToHarbor() throws IOException {
}
```

What do you think?

2022-05-04 08:08 UTC, sschnabe commented
Closing due of age.

2022-05-04 08:08 UTC, closed without merging