Add auth if helm binary url requires auth. #171
kokuwaio/helm-maven-plugin pull request #191
Opened 2022-05-12 14:29 UTC by nazarovkv

2022-05-13 06:32 UTC, sschnabe requested changes
Thanks for your pr. I have 3 minor comments.

Later i'll add invoker tests.

2022-05-13 06:32 UTC, sschnabe commented on src/main/java/io/kokuwa/maven/helm/AbstractHelmMojo.java
> +	@Parameter(property = "helm.downloadUser")
This can be moved to `InitMojo`. Please documentation to `README.md`.

2022-05-13 06:32 UTC, sschnabe commented on src/main/java/io/kokuwa/maven/helm/InitMojo.java
> +		if (!StringUtils.isBlank(getHelmDownloadUser())
`!StringUtils.isBlank` should be `StringUtils.isNotBlank`.

2022-05-13 06:32 UTC, sschnabe commented on src/main/java/io/kokuwa/maven/helm/InitMojo.java
> +		if (getSettings().getServer(getHelmDownloadServerId()) != null) {
Please store in a local variable to avoid duplicate lookup.

2022-05-13 07:57 UTC, sschnabe approved these changes

2022-05-13 10:46 UTC, nazarovkv commented
@fabian-schlegel please take a look.

2022-05-16 07:09 UTC, fabian-schlegel approved these changes

2022-05-16 07:09 UTC, merged